const courses = [
  {
    id: 1,
    title: "Learn React from Scratch",
    description: "Comprehensive course to learn React and its core libraries ",
    instructor: "John Smith",
    price: 199,
    image: "images/images1.jpg",
    rating: 2.5,
    reviews: 128,
  },
  {
    id: 2,
    title: "Advanced JavaScript",
    description: "Learn advanced concepts in JavaScript programming",
    instructor: "Sarah Johnson",
    price: 149,
    image: "images/images2.jpg",
    rating: 3.2,
    reviews: 87,
  },
  {
    id: 3,
    title: "UI Design with MUI",
    description: "Build beautiful user interfaces with Material-UI",
    instructor: "Michael Brown",
    price: 179,
    image: "images/images3.jpg",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 4,
    title: "Node.js for Beginners",
    description: "Learn to build server applications with Node.js",
    instructor: "Emily Davis",
    price: 229,
    image: "images/images2.jpg",
    rating: 2,
    reviews: 300,
  },
  {
    id: 5,
    title: "Database with MongoDB",
    description: "Working with NoSQL databases",
    instructor: "David Wilson",
    price: 159,
    image: "https://source.unsplash.com/random/300x200/?database",
    rating: 1.7,
    reviews: 1000,
  },
  {
    id: 6,
    title: "Full Stack Development",
    description: "Complete course covering frontend to backend development",
    instructor: "Jessica Taylor",
    price: 399,
    image: "https://source.unsplash.com/random/300x200/?webdevelopment",
    rating: 7,
    reviews: 600,
  },
];

export default courses;
